# Generated by Django 4.2.5 on 2023-09-27 19:43

from django.db import migrations, models
import faker.providers.job
import faker.providers.person


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_alter_teacher_first_name_alter_teacher_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(
                default=faker.providers.person.Provider.first_name, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(
                default=faker.providers.person.Provider.last_name, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(
                default=faker.providers.job.Provider.job, max_length=50
            ),
        ),
    ]
